import = ["/home/azat/.config/alacritty/themes/themes/breeze.toml"]

[font]
size = 16

[font.bold]
family = "Liberation Mono"
style = "Bold"

[font.bold_italic]
family = "Liberation Mono"
style = "Bold Italic"

[font.italic]
family = "Liberation Mono"
style = "Italic"

[font.normal]
family = "Liberation Mono"
style = "Regular"

[window]
opacity = 0.98
