#!/usr/bin/env bash

patterns=(
    # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=901831
    # https://bugs.chromium.org/p/chromium/issues/detail?id=879929
    'GetVSyncParametersIfAvailable()'

    'ERROR:gles2_cmd_decoder.cc'
)
patterns=( "${patterns[@]@Q}" )

exec chromium "$@" |& eval exec fgrep -v "$(printf -- "-e %s " "${patterns[@]}")"
