[[language]]
name = "rust"

[[language]]
name = "cpp"
[[language]]
name = "c"

[language-server.clangd.config]
fallbackFlags = ["-std=c++20"]

[language-server.rust-analyzer.config.check]
command = "clippy"
[language-server.rust-analyzer.config.cargo]
allFeatures = true
# read [lints.*] sections from the Cargo.toml
extraArgs = ["-Zlints"]
